#include <stdint.h>
#include <libk/ascii.h>
#include <drivers/keyboard/keyboard.h>

const kbd_event scancode_set1[KBD_SCAN_CODES] = {
    [0x01] = { ASCII_ESCAPE, ASCII_ESCAPE, KBD_MASK_NONE }, // ESC - Replace with ctrl msg
    [0x02] = { ASCII_ONE, ASCII_EXCLAMATION_MARK, KBD_MASK_SHIFT },
    [0x03] = { ASCII_TWO, ASCII_AT_SIGN, KBD_MASK_SHIFT },
    [0x04] = { ASCII_THREE, ASCII_NUMBER_SIGN, KBD_MASK_SHIFT },
    [0x05] = { ASCII_FOUR, ASCII_DOLLAR_SIGN, KBD_MASK_SHIFT },
    [0x06] = { ASCII_FIVE, ASCII_PERCENT, KBD_MASK_SHIFT },
    [0x07] = { ASCII_SIX, ASCII_CARET, KBD_MASK_SHIFT },
    [0x08] = { ASCII_SEVEN, ASCII_AMPERSAND, KBD_MASK_SHIFT },
    [0x09] = { ASCII_EIGHT, ASCII_ASTERISK, KBD_MASK_SHIFT },
    [0x0A] = { ASCII_NINE, ASCII_LEFT_PAREN, KBD_MASK_SHIFT },
    [0x0B] = { ASCII_ZERO, ASCII_RIGHT_PAREN, KBD_MASK_SHIFT },
    [0x0C] = { ASCII_MINUS, ASCII_UNDERSCORE, KBD_MASK_SHIFT },
    [0x0D] = { ASCII_EQUAL, ASCII_PLUS, KBD_MASK_SHIFT },
    [0x0E] = { KBD_INPUT_NONE, KBD_INPUT_NONE, KBD_MASK_NONE }, // Backspace - Replace with ctrl msg?
    [0x0F] = { ASCII_H_TAB, ASCII_H_TAB, KBD_MASK_NONE },
    [0x10] = { ASCII_LOWER_Q, ASCII_UPPER_Q, KBD_MASK_SHIFT },
    [0x11] = { ASCII_LOWER_W, ASCII_UPPER_W, KBD_MASK_SHIFT },
    [0x12] = { ASCII_LOWER_E, ASCII_UPPER_E, KBD_MASK_SHIFT },
    [0x13] = { ASCII_LOWER_R, ASCII_UPPER_R, KBD_MASK_SHIFT },
    [0x14] = { ASCII_LOWER_T, ASCII_UPPER_T, KBD_MASK_SHIFT },
    [0x15] = { ASCII_LOWER_Y, ASCII_UPPER_Y, KBD_MASK_SHIFT },
    [0x16] = { ASCII_LOWER_U, ASCII_UPPER_U, KBD_MASK_SHIFT },
    [0x17] = { ASCII_LOWER_I, ASCII_UPPER_I, KBD_MASK_SHIFT },
    [0x18] = { ASCII_LOWER_O, ASCII_UPPER_O, KBD_MASK_SHIFT },
    [0x19] = { ASCII_LOWER_P, ASCII_UPPER_P, KBD_MASK_SHIFT },
    [0x1A] = { ASCII_L_SQR_BRKT, ASCII_L_CURLY_BRKT, KBD_MASK_SHIFT },
    [0x1B] = { ASCII_R_SQR_BRKT, ASCII_R_CURLY_BRKT, KBD_MASK_SHIFT },
    [0x1C] = { ASCII_LINE_FEED, ASCII_LINE_FEED, KBD_MASK_NONE }, // ENTER replace with ctrl msg?
    [0x1D] = { KBD_INPUT_NONE, KBD_INPUT_NONE, KBD_MODIFIER | KBD_MASK_CTRL }, //LCTRL
    [0x1E] = { ASCII_LOWER_A, ASCII_UPPER_A, KBD_MASK_SHIFT },
    [0x1F] = { ASCII_LOWER_S, ASCII_UPPER_S, KBD_MASK_SHIFT },
    [0x20] = { ASCII_LOWER_D, ASCII_UPPER_D, KBD_MASK_SHIFT },
    [0x21] = { ASCII_LOWER_F, ASCII_UPPER_F, KBD_MASK_SHIFT },
    [0x22] = { ASCII_LOWER_G, ASCII_UPPER_G, KBD_MASK_SHIFT },
    [0x23] = { ASCII_LOWER_H, ASCII_UPPER_H, KBD_MASK_SHIFT },
    [0x24] = { ASCII_LOWER_J, ASCII_UPPER_J, KBD_MASK_SHIFT },
    [0x25] = { ASCII_LOWER_K, ASCII_UPPER_K, KBD_MASK_SHIFT },
    [0x26] = { ASCII_LOWER_L, ASCII_UPPER_L, KBD_MASK_SHIFT },
    [0x27] = { ASCII_SEMICOLON, ASCII_COLON, KBD_MASK_SHIFT },
    [0x28] = { ASCII_SINGLE_QUOTE, ASCII_DOUBLE_QOUTE, KBD_MASK_SHIFT },
    [0x29] = { ASCII_BACKTICK, ASCII_TILDE, KBD_MASK_SHIFT },
    [0x2A] = { KBD_INPUT_NONE, KBD_INPUT_NONE, KBD_MODIFIER | KBD_MASK_SHIFT }, //LSHIFT
    [0x2B] = { ASCII_BACKSLASH, ASCII_VERT_BAR, KBD_MASK_SHIFT },
    [0x2C] = { ASCII_LOWER_Z, ASCII_UPPER_Z, KBD_MASK_SHIFT },
    [0x2D] = { ASCII_LOWER_X, ASCII_UPPER_X, KBD_MASK_SHIFT },
    [0x2E] = { ASCII_LOWER_C, ASCII_UPPER_C, KBD_MASK_SHIFT },
    [0x2F] = { ASCII_LOWER_V, ASCII_UPPER_V, KBD_MASK_SHIFT },
    [0x30] = { ASCII_LOWER_B, ASCII_UPPER_B, KBD_MASK_SHIFT },
    [0x31] = { ASCII_LOWER_N, ASCII_UPPER_N, KBD_MASK_SHIFT },
    [0x32] = { ASCII_LOWER_M, ASCII_UPPER_M, KBD_MASK_SHIFT },
};

/* Maybe in the future :) */
//char scancode_set1[] = {};
//char scancode_set3[] = {};